- name: ansible to vars 
  hosts: web 
  vars: 
     course: "devops"
  tasks: 
    - name: ansible to install
      vars: 
       course: "aws"
      ansible.builtin.debug:
        msg: "my course is {{ course }}"