- name: ansible to variables 
  hosts: web 
  vars_prompt: 
   - name: username
     prompt: "enter ur username"
  tasks: 
    - name: "ansible to  print "
      ansible.builtin.debug:
        msg: "{{username }}"