- name : ansible variables 
  hosts: web 
  vars_prompt:
   - name: username 
     prompt: enter ur username 
  tasks:  
   - name: ansible to print a msg: 
     ansible.builtin.debug: 
        msg: "{{ username }}"
   