- name: ansible to  writwe wehen condition 
  hosts: web 
  become: yes
  vars: 
   num: 7
  tasks:  
    - name: ansible to write 
     
      ansible.builtin.debug: 
        msg: "hi my name is anveen"
      when: num >7  